<?php

return [

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/

    'files' => [
        realpath(__DIR__.'/../app/Providers/AppServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/BusServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/ConfigServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/ErrorServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/EventServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/FacadeServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/LogServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/RepositoryServiceProvider.php'),
        realpath(__DIR__.'/../app/Providers/RouteServiceProvider.php'),
    ],

    'providers' => [

    ]

];
